name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # If you ever add per-package lockfiles, list them here:
          # cache-dependency-path: |
          #   package-lock.json

      - name: Install (root + workspaces)
        run: npm ci --workspaces --include-workspace-root

      # Optional: quick sanity check that CI can resolve 'wouter'
      - name: Sanity check deps
        run: |
          echo "dep:" && node -p "require('./package.json').dependencies.wouter || 'missing'"
          echo "lock has wouter? " && node -p "Object.keys(require('./package-lock.json').packages).includes('node_modules/wouter') ? 'yes' : 'no'"
          node -p "require.resolve('wouter')" >/dev/null


      - name: Type check
        run: npm run check --silent || true

      - name: Build
        env:
          # Tina envs (from repo Settings → Secrets and variables → Actions)
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          NODE_ENV: production
        run: npm run build