name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root deps
        run: npm ci

      - name: Install journal deps
        run: |
          cd apps/journal
          npm ci

      - name: Type check
        run: npm run check --silent || true

      - name: Build
        run: npm run build

